server:
  port: 8089

spring:
  data:
    rest:
      base-path: /api

  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/h2/sample-db
    username: sa
    password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    root: info
    org.springframwork : debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace