server:
  port: 8081

---

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3002"
              - "http://localhost:3003"
              - "http://localhost:3011"
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
            allowedHeaders:
              - Context-Type
              - Content-Type
              - Accept
              - X-Requested-With
              - remember-me
              - Content-Disposition
              - Authorization
              - ssoKey
              - session
              - newToken
              - access-token
              - Access-Control-Expose-Headers
            allow-credentials: true
      default-filters:
        - name: GlobalFilter
          args:
            preFilter: true
            postFilter: true
      routes:
        - id: member-svc
          uri: http://localhost:8080/
          predicates:
            - Path=/member/**
          filters:
            - name: MemberFilter
              args:
                preFilter: true
                postFilter: true
        - id: shopping-svc
          uri: http://localhost:8089/
          predicates:
            - Path=/api/**
          filters:
            - name: MemberFilter
              args:
                preFilter: true
                postFilter: true

        - id: test-svc
          uri: http://localhost:9090/
          predicates:
            - Path=/resource1/**

  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/h2/sample-db
    username: sa
    password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    root: debug