server:
  port: 8081

---
spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
#          args:
#            preFilter: true
#            postFilter: true
      routes:
        - id: member-svc
          uri: http://localhost:8080/
          predicates:
            - Path=/member/**
          filters:
            - name: MemberFilter
#              args:
#                preFilter: true
#                postFilter: true

logging:
  level:
    root: debug