spring:
  data:
    rest:
      base-path: /member
  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/h2/sample-db
    username: sa
    password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

crypto:
  key: helloworld
