spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/study/member-api/member
    username: sa
    password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

crypto:
  key: helloworld
